
services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: Freshbasket_BD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: freshbasket_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Freshbasket_BD
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: freshbasket_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
